apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-ai-gateway-crds
  namespace: envoy-ai-gateway-system
spec:
  interval: 24h
  url: oci://docker.io/envoyproxy/ai-gateway-crds-helm
  ref:
    tag: "1.0.0"
