apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-ai-gateway
  namespace: envoy-ai-gateway-system
spec:
  interval: 24h
  url: oci://docker.io/envoyproxy/ai-gateway-helm
  ref:
    tag: "0.7.0"
