apiVersion: cloud.ogenki.io/v1alpha1
kind: App
metadata:
  name: wizard-e2e-platform
  namespace: apps
spec:
  image:
    repository: ghcr.io/stefanprodan/podinfo
    tag: 6.9.2
  route:
    enabled: true
    hostname: wizard-1
    internetFacing: false
    rules:
    - backendPort: 9898
      pathPrefix: /
  service:
    port: 9898
  type: web
