#!/usr/bin/env bash
# shellcheck disable=SC2015,SC2034,SC2329
# (ok/bad never fail, so `a && ok || bad` is a safe if/else; CLOUD, gen_password
# and store_value are read by the eval'd seed_body, which static analysis cannot see.)
# requires: jq
#
# gcp-0's CNPG superuser for ZITADEL is GENERATED by `secret-store.sh seed`
# (ADR-0052). zitadel-envvars, which AWS derives it from, does not exist on GCP,
# so without this the SQLInstance never gets a superuser and the deploy halts.
#
# Runs the real script against a stub gcloud: absent -> one `versions add`,
# the value never printed or on argv; present -> no write. AWS still derives.
set -uo pipefail
cd "$(dirname "$0")/../../.." || exit
fail=0
ok() { printf '  ok   %s\n' "$1"; }
bad() { printf '  FAIL %s\n' "$1"; fail=1; }

KEY="cnpg-xplane-zitadel-superuser"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
mkdir -p "$tmp/bin"

# The stub logs its argv, answers describe from $STUB_PRESENT, and keeps the
# payload of `versions add` in a file so the test can check its shape.
cat >"$tmp/bin/gcloud" <<'STUB'
#!/usr/bin/env bash
printf '%s\n' "$*" >>"$STUB_DIR/argv.log"
[ "$1 $2" = "auth application-default" ] && exit 1
args=" $* "
name=""
for a in "$@"; do case "$a" in -*|secrets|describe|create|versions|add|--project) ;; *) name="$a" ;; esac; done
case "$args" in
    *" describe "*)
        case " $STUB_PRESENT " in *" $name "*) exit 0 ;; esac
        echo "NOT_FOUND: Secret [$name] not found" >&2; exit 1 ;;
    *" versions add "*) cat >"$STUB_DIR/payload-$name"; exit 0 ;;
    *) exit 0 ;;
esac
STUB
chmod +x "$tmp/bin/gcloud"

others="harbor-admin-password harbor-valkey-password observability-victoria-metrics-k8s-stack-grafana-envvars cnpg-xplane-harbor-roles-harbor cnpg-xplane-image-gallery-roles-image-gallery-app"

run_seed() {
    rm -f "$tmp"/argv.log "$tmp"/payload-*
    STUB_DIR="$tmp" STUB_PRESENT="$1" PATH="$tmp/bin:$PATH" \
        bash scripts/provision/secret-store.sh seed --cloud gcp --project p --apply >"$tmp/out.log" 2>&1
}

# ── absent: generated once, never shown ───────────────────────────────────────
run_seed "$others"
adds="$(grep -c "versions add $KEY" "$tmp/argv.log" 2>/dev/null)"
[ "$adds" = "1" ] && ok "absent: one versions add for $KEY" || bad "absent: expected 1 versions add for $KEY, got ${adds:-0}"
other_adds="$(grep -c 'versions add' "$tmp/argv.log")"
[ "$other_adds" = "1" ] && ok "absent: nothing else written" || bad "absent: $other_adds writes, expected 1"
if [ -f "$tmp/payload-$KEY" ]; then
    user="$(jq -r .username "$tmp/payload-$KEY")"
    pw="$(jq -r .password "$tmp/payload-$KEY")"
    [ "$user" = "postgres" ] && ok "payload username is postgres" || bad "payload username is '$user'"
    if [[ "$pw" =~ ^[A-Za-z0-9]{32,}$ ]]; then ok "password is >=32 alphanumerics"; else bad "password is not >=32 alphanumerics (length ${#pw})"; fi
    if [ -n "$pw" ]; then
        grep -qF -- "$pw" "$tmp/out.log" && bad "the password was printed" || ok "the password is not printed"
        grep -qF -- "$pw" "$tmp/argv.log" && bad "the password reached argv" || ok "the password is not on argv"
    fi
else
    bad "no payload was written for $KEY"
fi

# ── present: never overwritten ────────────────────────────────────────────────
run_seed "$others $KEY"
grep -q 'versions add\|secrets --project p create\| create ' "$tmp/argv.log" \
    && bad "present: a write happened" || ok "present: no write"

# ── AWS keeps deriving from zitadel-envvars ───────────────────────────────────
body="$(sed -n '/^seed_body() {/,/^}/p' scripts/provision/secret-store.sh)"
[ -n "$body" ] || { echo "could not extract seed_body()" >&2; exit 1; }
eval "$body"
gen_password() { printf 'GENERATEDGENERATEDGENERATED00000'; }
store_value() { printf '{"ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD":"derived-from-envvars"}'; } # pragma: allowlist secret
CLOUD=aws
got="$(seed_body "cnpg/xplane-zitadel/superuser" | jq -r .password)"
[ "$got" = "derived-from-envvars" ] && ok "aws: derived from zitadel-envvars" || bad "aws: got '$got', expected the derived value"
CLOUD=gcp
got="$(seed_body "$KEY" | jq -r .password)"
[ "$got" = "GENERATEDGENERATEDGENERATED00000" ] && ok "gcp: generated, not derived" || bad "gcp: got '$got', expected the generated value"

exit "$fail"
