apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github-commit-status
  namespace: flux-system
spec:
  providerRef:
    name: github-commit-status
  eventSources:
    - kind: Kustomization
      name: "flux-system"
    - kind: Kustomization
      name: "flux-artifact-generators"
