#!/usr/bin/env bash
# Managed-store key -> OpenBao path, the one copy (GCP parity GP-5). Read by
# secret-store.sh's `migrate` and by zitadel-oidc-clients.sh's --mirror-openbao.
# Why the map is explicit and what must stay out of it: see the comment kept
# above the function below.

# Managed-store key -> OpenBao path, for `migrate`.
#
# Explicit rather than derived, because the managed store's names are not
# uniform: ADR-0023 introduced the dash form, slash-form names predate it, and
# the cnpg/* ones are generated by secret-store.sh's `seed` rather than curated by a human.
#
# Anything not listed is SKIPPED and reported, never guessed. A wrong guess here
# writes a platform secret into an app's prefix, which is a privilege boundary
# rather than a cosmetic mistake.
#
# Four keys are deliberately absent and must stay so:
#   certificates/*/ca-chain        bootstrap tier -- read before OpenBao is up,
#                                  and the OpenBao-backed store needs the Secret
#                                  it produces, so repointing it is circular
#   cnpg/*  (three of them)        the SQLInstance composition hardcodes
#                                  `secretStoreRef.name: clustersecretstore` and
#                                  its XRD exposes no store field, so the claim
#                                  cannot be repointed -- the same blocker App
#                                  had before crossplane-configuration v0.6.1.
#                                  NOT because a machine writes them: `seed`
#                                  creates them (they are in GENERATABLE)
#                                  and it is operator-run. Nothing in the
#                                  cluster writes to any secret store.
bao_target_for() {
    case "$1" in
        harbor-admin-password) printf 'platform/harbor/admin-password' ;;
        harbor-oidc) printf 'platform/harbor/oidc' ;;
        harbor-valkey-password) printf 'platform/harbor/valkey-password' ;;
        headlamp-envvars) printf 'platform/headlamp/envvars' ;;
        zitadel-envvars) printf 'platform/zitadel/envvars' ;;
        runlore-credentials) printf 'platform/runlore/credentials' ;;
        runlore-slack-app) printf 'platform/runlore/slack-app' ;;
        runlore-webhook) printf 'platform/runlore/webhook' ;;
        security-flux-ui-oidc) printf 'platform/flux/ui-oidc' ;;
        observability-flux-slack-app) printf 'platform/flux/slack-app' ;;
        observability-victoria-metrics-k8s-stack-grafana-envvars) printf 'platform/victoria-metrics/grafana-envvars' ;;
        observability-victoria-metrics-k8s-stack-alertmanager-slack-app) printf 'platform/victoria-metrics/alertmanager-slack-app' ;;
        tailscale-k8s-operator-oauth-client) printf 'platform/tailscale/operator-oauth-client' ;;
        apps-app-wizard-llm) printf 'apps/app-wizard/llm' ;;
        apps-app-wizard-oauth) printf 'apps/app-wizard/oauth' ;;
        apps/image-gallery/config) printf 'apps/image-gallery/config' ;;
        *) return 1 ;;
    esac
}
