apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vmrule.yaml
  - vmrule-logs.yaml
  - grafana-folder.yaml
  - grafana-dashboard.yaml
  - grafana-dashboard-agent-run.yaml
  - grafana-dashboard-agent-fleet.yaml
  - agent-traces-collector.yaml
  - referencegrant-agent-traces.yaml
