apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oncall-valkey
  namespace: tooling
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: observability/oncall/valkey
  refreshInterval: 20m
  secretStoreRef:
    kind: ClusterSecretStore
    name: clustersecretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: oncall-valkey
