apiVersion: v1
kind: Service
metadata:
  name: octo-sts
  namespace: agent-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: octo-sts
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
