apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: victoria-metrics-k8s-stack-grafana-envvars
  namespace: observability
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: victoria-metrics/grafana-envvars
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-platform
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: victoria-metrics-k8s-stack-grafana-envvars
